image:
- Visual Studio 2017
- Ubuntu
version: 1.6.7.{build}
configuration: Release
skip_branch_with_pr: true
install:
- git submodule update --init --recursive
assembly_info:
  patch: true
  file: Sources\AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: |
    dotnet build Sources/PT.PM.sln -c Release

    dotnet publish Sources/PT.PM.Cli/PT.PM.Cli.csproj -c Release -o ../../bin/Cli/netcoreapp2.1 -f netcoreapp2.1

    dotnet publish Sources/PT.PM.PatternEditor/PT.PM.PatternEditor.csproj -c Release -o ../../bin/Gui/netcoreapp2.1 -f netcoreapp2.1

    if ($isWindows) {
        dotnet publish Sources/PT.PM.Cli/PT.PM.Cli.csproj -c Release -o ../../bin/Cli/net472 -f net472

        dotnet publish Sources/PT.PM.PatternEditor/PT.PM.PatternEditor.csproj -c Release -o ../../bin/Gui/net472 -f net472
    }
test_script:
- ps: |
    dotnet test Sources/PT.PM.Tests/PT.PM.Tests.csproj -c Release
    dotnet test Sources/PT.PM.CSharpParseTreeUst.Tests/PT.PM.CSharpParseTreeUst.Tests.csproj -c Release
after_test:
- ps: |
    cd bin/Cli/netcoreapp2.1

    7z a PT.PM.Cli-netcoreapp2.1-$env:APPVEYOR_BUILD_VERSION.zip *.dll *.config *.json runtimes

    Push-AppveyorArtifact PT.PM.Cli-netcoreapp2.1-$env:APPVEYOR_BUILD_VERSION.zip

    cd ../../Gui/netcoreapp2.1

    7z a PT.PM.Gui-netcoreapp2.1-$env:APPVEYOR_BUILD_VERSION.zip *.dll *.config *.json runtimes

    Push-AppveyorArtifact PT.PM.Gui-netcoreapp2.1-$env:APPVEYOR_BUILD_VERSION.zip

    if ($isWindows) {
        cd ../../Cli/net472

        7z a PT.PM.Cli-net472-$env:APPVEYOR_BUILD_VERSION.zip *.exe *.dll *.config

        Push-AppveyorArtifact PT.PM.Cli-net472-$env:APPVEYOR_BUILD_VERSION.zip

        cd ../../Gui/net472

        7z a PT.PM.Gui-net472-$env:APPVEYOR_BUILD_VERSION.zip *.exe *.dll *.config

        Push-AppveyorArtifact PT.PM.Gui-net472-$env:APPVEYOR_BUILD_VERSION.zip
    }
