image:
- Visual Studio 2017
- Ubuntu
version: 1.5.1.{build}
configuration: Release
skip_branch_with_pr: true
install:
- git submodule update --init --recursive
assembly_info:
  patch: true
  file: Sources\AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: ./build-release.cmd
test_script:
- ps: >-
    cd Tests/Release/netcoreapp2.0

    dotnet vstest PT.PM.Cli.Tests.dll PT.PM.CSharpParseTreeUst.Tests.dll PT.PM.Dsl.Tests.dll PT.PM.JavaParseTreeUst.Tests.dll PT.PM.JavaScriptParseTreeUst.Tests.dll PT.PM.Matching.Tests.dll PT.PM.PhpParseTreeUst.Tests.dll PT.PM.SqlParseTreeUst.Tests.dll PT.PM.Tests.dll --logger:nunit

    cd ../../..

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path ./Tests/Release/netcoreapp2.0/TestResults/TestResults.xml))
after_test:
- ps: >-
    cd bin/Cli

    7z a PT.PM.Cli-$env:APPVEYOR_BUILD_VERSION.zip *.dll *.config *.json runtimes

    cd ../Gui
    
    7z a PT.PM.Gui-$env:APPVEYOR_BUILD_VERSION.zip *.dll *.config *.json runtimes
artifacts:
- path: bin/Cli/*.zip
  name: PT.PM.Cli
- path: bin/Gui/*.zip
  name: PT.PM.Gui