os: Visual Studio 2017
version: 1.5.3.{build}
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
install:
- cmd: git submodule update --init --recursive
assembly_info:
  patch: true
  file: Sources\AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: generate.cmd
build_script: >-
    dotnet build Sources/PT.PM.Gui.sln -c %CONFIGURATION%

    dotnet publish Sources/PT.PM.Cli/PT.PM.Cli.csproj -c %CONFIGURATION% -o ../../bin/Cli

    dotnet publish Sources/PT.PM.PatternEditor/PT.PM.PatternEditor.csproj -c %CONFIGURATION% -o ../../bin/Gui
test_script:
- cmd: >-
    cd Tests/%CONFIGURATION%/netcoreapp2.0

    dotnet vstest PT.PM.Cli.Tests.dll

    dotnet vstest PT.PM.CSharpParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Dsl.Tests.dll

    dotnet vstest PT.PM.JavaParseTreeUst.Tests.dll

    dotnet vstest PT.PM.JavaScriptParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Matching.Tests.dll

    dotnet vstest PT.PM.PhpParseTreeUst.Tests.dll

    dotnet vstest PT.PM.SqlParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Tests.dll

    cd ../../..
after_test:
- cmd: >-
    cd bin/Cli

    7z a PT.PM.Cli-%APPVEYOR_BUILD_VERSION%.zip *.dll *.config *.json runtimes

    cd ../Gui
    
    7z a PT.PM.Gui-%APPVEYOR_BUILD_VERSION%.zip *.dll *.config *.json runtimes
artifacts:
- path: bin/Cli/*.zip
  name: PT.PM.Cli
- path: bin/Gui/*.zip
  name: PT.PM.Gui