os: Visual Studio 2017
version: 1.5.3.{build}
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
install:
- cmd: git submodule update --init --recursive
assembly_info:
  patch: true
  file: Sources\AssemblyInfoCommon.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: generate.cmd
build_script:
  - dotnet build Sources/PT.PM.Gui.sln -c %CONFIGURATION%
test_script:
- cmd: >-
    cd Tests/%CONFIGURATION%/netcoreapp2.0

    dotnet vstest PT.PM.Cli.Tests.dll

    dotnet vstest PT.PM.CSharpParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Dsl.Tests.dll

    dotnet vstest PT.PM.JavaParseTreeUst.Tests.dll

    dotnet vstest PT.PM.JavaScriptParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Matching.Tests.dll

    dotnet vstest PT.PM.PhpParseTreeUst.Tests.dll

    dotnet vstest PT.PM.SqlParseTreeUst.Tests.dll

    dotnet vstest PT.PM.Tests.dll