version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: bash generate.cmd
      - run: dotnet build Sources/PT.PM.sln -c Release
      - cd Tests/Release/netcoreapp2.0
      - run: dotnet vstest PT.PM.Cli.Tests.dll PT.PM.CSharpParseTreeUst.Tests.dll PT.PM.Dsl.Tests.dll PT.PM.JavaParseTreeUst.Tests.dll PT.PM.JavaScriptParseTreeUst.Tests.dll PT.PM.Matching.Tests.dll PT.PM.PhpParseTreeUst.Tests.dll PT.PM.SqlParseTreeUst.Tests.dll PT.PM.Tests.dll
      - cd ../../..
